//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlamlyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_duplicator_packages
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public string hash { get; set; }
        public int status { get; set; }
        public System.DateTime created { get; set; }
        public string owner { get; set; }
        public byte[] package { get; set; }
    }
}
