//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlamlyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_glamly_servicesbookings
    {
        public int id { get; set; }
        public string bookingid { get; set; }
        public string service { get; set; }
        public string type { get; set; }
        public string datetime { get; set; }
        public string altdatetime { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string personal { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string billingaddress { get; set; }
        public string message { get; set; }
        public string newsletter { get; set; }
        public string status { get; set; }
        public Nullable<int> userid { get; set; }
        public string isedit { get; set; }
        public string servicewithtypes { get; set; }
        public string otherservices { get; set; }
        public string isdeleted { get; set; }
        public Nullable<int> stylistid { get; set; }
        public Nullable<int> workflowstatus { get; set; }
    }
}
