//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlamlyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_glamly_payment
    {
        public int id { get; set; }
        public string acquirer { get; set; }
        public string amount { get; set; }
        public string approvalcode { get; set; }
        public string calcfee { get; set; }
        public string cardexpdate { get; set; }
        public string cardnomask { get; set; }
        public string cardprefix { get; set; }
        public string cardtype { get; set; }
        public string currency { get; set; }
        public string dibsInternalIdentifier { get; set; }
        public string fee { get; set; }
        public string fullreply { get; set; }
        public string lang { get; set; }
        public string merchant { get; set; }
        public string merchantid { get; set; }
        public string method { get; set; }
        public string mobilelib { get; set; }
        public string orderid { get; set; }
        public string paytype { get; set; }
        public string platform { get; set; }
        public string status { get; set; }
        public string test { get; set; }
        public string textreply { get; set; }
        public string theme { get; set; }
        public string timeout { get; set; }
        public string transact { get; set; }
        public string version { get; set; }
        public int userid { get; set; }
        public string servicewithtypes { get; set; }
        public string bookingid { get; set; }
        public string paymentdate { get; set; }
        public string isdeleted { get; set; }
    }
}
