//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlamlyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_glamly_userresetpassword
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string userkey { get; set; }
        public Nullable<System.DateTime> requesttime { get; set; }
    }
}
